
export enum MarketRegime {
  RISK_ON = 'RISK_ON',
  RISK_OFF = 'RISK_OFF',
  NEUTRAL = 'NEUTRAL'
}

export interface AssembledConfig {
  initialCapital: number; 
  volTarget: number; 
  maxDrawdownLimit: number; 
  kellyScale: number; 
  atrStopMultiplier: number;
  useHRP: boolean;
  discordWebhookUrl?: string;
  enableAutomation: boolean;
  tradingIntervalSeconds: number;
  autoHedge: boolean;
  skipPull: boolean;
  watchlist: string[]; // List of tickers to track
}

export interface AssetSignal {
  ticker: string;
  name: string;
  price: number;
  changePercent: number; 
  trendScore: number; 
  mlConfidence: number; 
  volatility: number;
  signal: 'BUY' | 'SELL' | 'HOLD';
  sector: string;
  atr: number;
  volume: number;
  volumeAvg: number;
  rsi: number;
  macd: number;
  macdSignal: number; 
  insiderActivity: number; 
  newsSentimentImpact: number; 
  logisticsRisk: number; 
  discoverySource: 'MANUAL' | 'AI_NEWS_SCAN' | 'INSIDER_SCAN'; 
  compositeScore: number; 
  regime?: MarketRegime; 
  detectedPattern?: string; 
  
  // Trend
  sma50: number;
  sma200: number;
  ema20: number;
  adx: number;
  ichimokuStatus: 'ABOVE_CLOUD' | 'INSIDE_CLOUD' | 'BELOW_CLOUD';

  // Momentum
  stochK: number;
  stochD: number;
  cci: number; 

  // Volatility
  bollingerUpper: number;
  bollingerLower: number;

  // Volume
  obv: number; 
  vwap: number; 
}

export interface PortfolioPosition {
  ticker: string;
  shares: number;
  weight: number;
  entryPrice: number;
  currentPrice: number;
  pnl: number;
  pnlPercent: number;
}

export interface TradeExecution {
  id: string;
  ticker: string;
  side: 'BUY' | 'SELL';
  entryTime: string;
  exitTime?: string; 
  entryPrice: number;
  exitPrice?: number;
  quantity: number;
  status: 'OPEN' | 'CLOSED';
  grossPnl: number;
  fees: number;
  netPnl: number;
  strategy: string; 
  autoGenerated: boolean;
}

export interface BacktestMetric {
  date: string;
  equity: number;
  benchmark: number;
  drawdown: number;
  regime: MarketRegime;
}

export interface NewsItem {
  id: string;
  source: 'CNBC' | 'Telegram' | 'Reuters' | 'Bloomberg' | 'WSJ' | 'Insider' | 'Logistics' | 'Finnhub';
  relatedTicker?: string; 
  author?: string; 
  title: string;
  summary: string;
  sentiment: 'POSITIVE' | 'NEGATIVE' | 'NEUTRAL';
  impactScore: number; 
  timestamp: string;
  url?: string; 
}

export interface InsiderTrade {
  id: string;
  ticker: string;
  person: string;
  role: string; 
  type: 'BUY' | 'SELL';
  amount: number;
  date: string;
}

export interface ShippingRoute {
  id: string;
  name: string; 
  status: 'Normal' | 'Congested' | 'Blocked';
  costIndex: number; 
  trend: 'UP' | 'DOWN' | 'FLAT';
}

export interface EconomicEvent {
  id: string;
  event: string;
  country: string;
  impact: 'HIGH' | 'MEDIUM' | 'LOW';
  date: string;
  actual?: string;
  forecast?: string;
  previous?: string;
}

export interface SystemStatus {
  lastUpdated: string;
  vix: number;
  sentimentScore: number; 
  gprIndex: number; 
  regime: MarketRegime;
  activePositions: number;
  cashPosition: number;
  dailyPnl: number;
  isLive: boolean;
}

export interface ApiKeys {
  finnhub: string;
  alphaVantage: string;
}

export interface RiskMetrics {
  var95: number; 
  var99: number; 
  cvar95: number; 
  sharpeRatio: number;
  volatility: number;
  beta: number;
}

export interface PortfolioTarget {
  ticker: string;
  currentWeight: number; 
  targetWeight: number; 
  action: 'BUY' | 'SELL' | 'HOLD';
  sharesDiff: number; 
  reason: string; 
}

export type PipelineStage = 'IDLE' | 'PULL' | 'RESAMPLE' | 'QC' | 'COST' | 'EXECUTE' | 'BACKTEST' | 'PORTFOLIO' | 'DONE' | 'ERROR';

export interface PipelineLog {
  id: string;
  timestamp: string;
  stage: PipelineStage;
  message: string;
  type: 'INFO' | 'WARNING' | 'ERROR' | 'SUCCESS';
}

export interface PipelineArtifact {
  id: string;
  name: string; 
  path: string; 
  type: 'FILE' | 'REPORT' | 'DB';
  size: string;
  timestamp: string;
  status: 'GENERATED' | 'PENDING';
}

export interface HistoricalCandle {
  date: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}
