
import { AssetSignal, AssembledConfig, TradeExecution } from '../types';

/**
 * AUTOMATION & ALERTING SERVICE
 * 
 * V2: News-Driven Logic
 */

export const checkAutomatedTriggers = async (
  signals: AssetSignal[],
  config: AssembledConfig,
  lastTradeCount: number
): Promise<TradeExecution | null> => {
  if (!config.enableAutomation) return null;

  // PRIORITIZE NEWS DRIVEN OPPORTUNITIES
  // Find assets with high News Sentiment OR High ML Confidence
  
  const opportunity = signals.find(s => {
    const isNewsDriven = s.newsSentimentImpact >= 7 && s.rsi < 70; // Strong news, not yet overbought
    const isTechnical = s.mlConfidence > 0.85 && s.rsi < 40 && s.signal === 'BUY';
    
    return isNewsDriven || isTechnical;
  });
  
  // Throttle for demo: 5% chance per tick to execute if conditions met
  if (opportunity && Math.random() > 0.95) {
    
    const isNewsPlay = opportunity.newsSentimentImpact >= 7;
    const strategyName = isNewsPlay ? 'News_Event_Scalp_v1' : 'ML_Trend_Follow_v32';

    const trade: TradeExecution = {
      id: `auto-${Date.now()}`,
      ticker: opportunity.ticker,
      side: 'BUY',
      entryTime: new Date().toISOString(),
      entryPrice: opportunity.price > 0 ? opportunity.price : 100, // Fallback if 0
      quantity: Math.floor((config.initialCapital * 0.05) / (opportunity.price || 100)), // 5% position
      status: 'OPEN',
      grossPnl: 0,
      fees: 1.50, 
      netPnl: -1.50,
      strategy: strategyName,
      autoGenerated: true
    };

    if (config.discordWebhookUrl) {
      sendDiscordAlert(config.discordWebhookUrl, trade, opportunity, isNewsPlay);
    }

    return trade;
  }

  return null;
};

const sendDiscordAlert = async (url: string, trade: TradeExecution, signal: AssetSignal, isNews: boolean) => {
  const color = isNews ? 10181046 : 3066993; // Purple for News, Green for Tech
  const titlePrefix = isNews ? "📰 NEWS-DRIVEN ENTRY" : "🤖 TECH-ALGO ENTRY";

  const payload = {
    content: `**${titlePrefix}: ${trade.ticker}**`,
    embeds: [
      {
        title: `Executing ${trade.side} on ${trade.ticker}`,
        description: isNews ? "High sentiment impact detected from recent news flow." : "ML Model confidence threshold breached.",
        color: color,
        fields: [
            { name: "Price", value: `$${trade.entryPrice.toFixed(2)}`, inline: true },
            { name: "Size", value: `${trade.quantity} shares`, inline: true },
            { name: "Source", value: signal.discoverySource, inline: true },
            { name: "News Impact", value: `${signal.newsSentimentImpact}/10`, inline: true }
        ],
        footer: { text: "Assembled Trading AI - Live Execution" },
        timestamp: new Date().toISOString()
      }
    ]
  };

  try {
    await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
    });
  } catch (e) {
      console.error("Failed to send Discord alert", e);
  }
};
